# Derin Öğrenme için Temel Matematik

In [ ]:
%load_ext watermark

In [1]:
from IPython.display import Image
%matplotlib inline

### Skalerler, Vektörler, Matrisler ve Tensörler


- **Skalerler:** Skalerler, tek bir sayıdan oluşmaktadır.
- **Vektörler:** Bir vektör, bir sayı dizisidir. Bu sayıların her biri belirli bir düzen içerisindedir ve bu sayılara bu düzen içindeki sıralamasından yararlanarak erişebiliriz. 
    - $\mathbf{x}$ gibi belirtilen bir vektörün ilk elemanı $\mathbf{x_1}$, ikinci elemanı $\mathbf{x_2}$ vb. şekilde tanımlanmaktadır.
    - Vektörün sahip olduğu değerlerin ne tür olduğu belirtilmelidir. Eğer vektörün her elemanı $\mathbb{R}$ kümesinin bir elemanı ise ve bu vektörün n adet elemanı varsa, bu vektör $\mathbb{R}$ ve n sayısının kartezyen çarpımından ortaya çıkan ve $\mathbb{R}^{n}$ şeklinde gösterilen kümede yer almaktadır.

       $$ \mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ .. \\ x_n \end{bmatrix}$$
   
    - Bazı durumlarda vektörlerin elemanlarından oluşan bir kümeyi indekslememiz gerekebilir. Bu durumda, bu indislerden oluşan bir küme tanımlayıp, bu kümeyi altindiste belirterek bu elemanlara erişebiliriz. Örneğin bir kümedeki $x_1$, $x_3$, ve $x_6$, elemanlarına erişmek için önce bir S = {1,3,6} kümesini tanımlayıp daha sonra  $\mathbf{x_S}$ yazabiliriz.
    -  $\mathbf{x_{-1}}$ vektörü,  $\mathbf{x}$ vektörünün  $x_1$ hariç bütün elemanlarını içeren kümeyi temsil eder. $\mathbf{x_{-S}}$ vektörü ise yine $\mathbf{x}$ vektörünün $x_1$, $x_3$ ve $x_6$ elemanlarının çıkartılmış halini gösterir.


- **Matrisler:** Matrisler iki boyutlu sayı dizileridir ve her elemanları bir yerine iki indisle temsil edilir. 

    - Eğer gerçel değerlerden oluşan bir **A** matrisinin uzunluğu *m* genişliği *n* ise bu matris $\mathbb{R}^{mxn}$ kümesinin içindedir. Matris gösteriminde indisleri virgülle ayıracağız. Örneğin,  $\large\boldsymbol{A_{1,1}}$ soldaki en üst elemanı belirtirken, $\large\boldsymbol{A_{m,n}}$ ise en altta sağdaki elemanı belirtmektedir.

    $$ \large\boldsymbol{A} = \begin{bmatrix} A_{1,1} & A_{1,2} \\ A_{2,1} & A_{2,2} \end{bmatrix}$$

    - $\large\boldsymbol{A_{i,:}}$,  $\large\boldsymbol{A}$ matrisinin düşey koordinatlarının i olduğu yatay bir kesinti ifade eder. $\large\boldsymbol{A}$ matrisinin i'inci satırı.
    - $\large\boldsymbol{A_{:,i}}$ ise $\large\boldsymbol{A}$ matrisinin i'inci sütununu belirtir.

- **Tensörler:** Bazı durumlarda ikiden fazla ekseni olan dizilere ihtiyaç duyabiliriz. En genel tanımında, düzenli bir ızgara üzerine yerleştirilmiş ve değişken sayıda ekseni bulunan diziler tensör olarak adlandırılır.

- $\mathbf{A}$ tensörünün (i, j, k) koordinatlarındaki bir elemanını $A_{i,j,k}$ ifadesiyle göstereceğiz.

- **Transpoz:** Bir matrisin transpozu, o matrisin **ana köşegen** çizgisi etrafında aynalanmış halidir. Ana köşegen matrisin üst sol köşesinden sağ alt köşesine uzanır. Transpoz operasyonunun bir gösterimi için şekil-1'e bakınız.
- $\large\boldsymbol{A}$ matrisinin transpozunu $\large\boldsymbol{A^T}$ ifadesini kullanarak gösteriyoruz. Bu operasyon,

$$ (A^T)_{i,j} = A_{j,i} $$ ifadesiyle tanımlıdır.

- Vektörler tek bir sütun içeren matrisler olarak düşünülebilir. Dolayısıyla bir vektörün transpozu tek bir satır içeren bir matristir. 

$$ \large\boldsymbol{A} = \begin{bmatrix} A_{1,1} & A_{1,2} \\ A_{2,1} & A_{2,2} \\ A_{3,1} & A_{3,2} \end{bmatrix} $$

$$ A^T = \begin{bmatrix} A_{1,1} & A_{2,1} & A_{3,1} \\ A_{1,2} & A_{2,2} & A_{3,2} \end{bmatrix} $$

- Bir vektör satır içinde bir satır matrisi olarak yazıp daha sonra transpoz operatörüyle standart bir sütun vektörü olarak kullanmaktayız. Örneğin, 
$$ \mathbf{x} = [\mathbf{x_1}, \mathbf{x_2}, \mathbf{x_3}]^T $$

- Skaler, tek boyutlu matris olarak ele alınabilir. Bu durumda skaler'in transpozu yine kendisine eşittir.
$$ a = a^T$$

- İki matris birbiriyle toplanabilir. Bunu karşılıklı elemanlarını toplayarak yaparız: 
$$ \normalsize\boldsymbol{C} =  \normalsize\boldsymbol{A} + \normalsize\boldsymbol{B} -->  \normalsize\boldsymbol{C_{i,j}} =  \normalsize\boldsymbol{A_{i,j}} + \normalsize\boldsymbol{B_{i,j}}$$

- Bir matrise skaler eklenebilir ya da bir matrisi skalerle çarpabiliriz.
$$ \normalsize\boldsymbol{D} =  a \normalsize\boldsymbol{B} + \normalsize\boldsymbol{c} $$

**Ek:**
- Tüm makine öğrenmesi sistemleri temel veri yapısı olarak genellikle tensörleri kullanırlar. Tensör?
- Temel olarak tensörler veriler için taşıyıcı vazifesini görür ve genellikle sayısal veriler tutar. O zaman sayılar için taşıyıcı diyebiliriz. Matrislere (2 boyutlu tensörler) aşina olabilirsiniz: O zaman tensörler matrislerin herhangi bir boyuta genelleştirilmesidir.
- Skalerler (0B Tensörler): Bir eleman taşıyan tensörler skaler (skaler tensör, 0B tensör veya 0 boyutlu tensör) denir.
- Numpy kütüphanesinde mevcut olan float32 ve float64 sayılar birer skaler tensörüdür. Numpy kullanarak bir tensörün kaç ekseni olduğunu öğrenmek için dim niteliğini kullanarak belirlenebilir.
- Skaler sıfır eksene sahiptir. Bir tensörün eksen sayısı aynı zamanda tensörün derecesi olarak adlandırılmaktadır.

In [1]:
import numpy as np
sca = np.array(8)
sca

array(8)

In [2]:
sca.ndim

0

- **Vektörler (1B Tensörler):** Sayı dizilerine vektör ya da 1B tensör denir. 1B bir tensör sadece bir eksene sahiptir.

In [3]:
vec = np.array([1, 2, 3, 4, 5, 6])
vec

array([1, 2, 3, 4, 5, 6])

In [4]:
vec.ndim

1

- x vektörü 6 elemana sahiptir. Dolayısıyla bu vektör 6 boyutludur denebilir. Fakat tensör boyutu ile vektör boyutları karıştırılmamalıdır. Vektörler 1B tensörle olmakla beraber sahip oldukları eleman sayısı kadar da ilgili vektörün boyutu vardır. Yukarıda örnek olduğu gibi x vektörü 1B tensördür. Aynı zamanda x vektörü 6 boyutludur (6B).

- **Matrisler (2B Tensörler):** Bir vektör dizisi matris veya 2B tensördür. Bir matrisin iki ekseni vardır (satır ve sütun).

In [5]:
mat = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [6]:
mat.ndim

2

* **3B ve Daha Fazla Boyutlu Tensörler:**
    - Matrisleri bir dizide birleştirip 3B ve daha fazla boyutlu tensörler elde edilebilir.

In [7]:
tens = np.array([[[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]],
             [[5,4,3,2,1],
             [3,4,5,6,7],
             [10,1,2,5,9]],
             [[20,24,53,20,1],
             [3,30,90,21,14],
             [8,5,3,20,50]]])
tens

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[ 5,  4,  3,  2,  1],
        [ 3,  4,  5,  6,  7],
        [10,  1,  2,  5,  9]],

       [[20, 24, 53, 20,  1],
        [ 3, 30, 90, 21, 14],
        [ 8,  5,  3, 20, 50]]])

In [8]:
tens.ndim

3

* Tensörlerin 3 temel özelliği
    - **Eksen sayısı (derecesi):** 3B tensörlerin ük ekseni mevcutken matrislerin iki ekseni vardır.
    - **Şekli:** Her eksende kaç boyut olduğunu belirten sayılardır. Örneğin yukarıdaki matrisin şekli (3,5), 3B tensör örneğimizin ise (3,3,5)'dir. Vektörün şekli ise (6,) dır.
    - **Veri tipi:** Tensörün taşıdığı verinin tipini söyler. Örneğin, float23, float64, int16

In [9]:
sca.shape, vec.shape, mat.shape, tens.shape

((), (6,), (3, 5), (3, 3, 5))

In [10]:
sca.dtype, vec.dtype, mat.dtype, tens.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [11]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [12]:
train_images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [13]:
print(train_images.ndim)

3


In [14]:
print(train_images.shape)

(60000, 28, 28)


In [15]:
print(test_images.shape)

(10000, 28, 28)


- 3B tensörümüz
- 28x28 boyutundaki matrislerden 60000 adet bulunduran bir dizimiz var.
- Her matris 0 ile 255 arasında değer alıyor ve gri ölçeğinde bir görüntüye sahibiz.

In [16]:
print(train_images.dtype)

uint8


- 8 bitlik görüntüler

In [17]:
import matplotlib.pyplot as plt

digit = train_images[2]

plt.imshow(digit, cmap=plt.cm.binary)
plt.show()

<Figure size 640x480 with 1 Axes>

* **Kullanılan Tensör Verileri:**
    - **Vektör Verisi:** 2B tensörler (Vektör Dizisi) (örnekler, öznitelikler)
    - **Zaman serisi ya da ardışık veri:** 3B tensörler (örnekler, zaman_adımı, öznitelikler)
    - **Görüntüler:** 4B tensörler (Örnekler, yükseklik, genişlik, kanallar) ya da (örnekler, kanallar, yükseklik, genişlik)
    - **Video:** 5B tensörler (örnekler, kareler, yükseklik, genişlik, kanallar) ya da (örnekler, kareler, kanallar, yükseklik, genişlik)

### Matris ve Vektörleri Çarpmak

**Matris Çarpımı:**
    - A ve B matrisini ele alalım. 
$$ \normalsize\boldsymbol{C} =  \normalsize\boldsymbol{A} \normalsize\boldsymbol{B} $$

- Çarpım işleminin gerçekleşmesi için $\normalsize\boldsymbol{A}$ sütun sayısıyla $\normalsize\boldsymbol{B}$ matrisinin satır sayısı eşit olmalıdır.
- $\normalsize\boldsymbol{A}$ matrisinin şekli mxn ve $\normalsize\boldsymbol{B}$ matrisinin şekli nxp ise $\normalsize\boldsymbol{C}$ matrisinin şekli mxp kadardır
- Çarpım işlemi,
$$ \large\boldsymbol{C_{i,j}} = \sum_k \large\boldsymbol{A_{i,k}} \large\boldsymbol{B_{k,j}} $$
ifadesiyle tanımlanmıştır.

In [18]:
import numpy as np
 

matx1 = np.array([np.arange(0,3), np.arange(3,6)])
matx2 = np.array([np.arange(0,2), np.arange(2,4), np.arange(4,6)])
 
print(matx1)
print("Matris-1 shape: ", matx1.shape)
print("\n")
print(matx2)
print("Matris-2 shape: ", matx2.shape)
 

[[0 1 2]
 [3 4 5]]
Matris-1 shape:  (2, 3)


[[0 1]
 [2 3]
 [4 5]]
Matris-2 shape:  (3, 2)


- **Skaler Çarpım:** Skaler bir değerin, matrisin bütün elemanlarıyla çarpımı.
- **Dot Product - İç Çarpım:** İki matrisin, matris kurallarına göre çarpımı

In [19]:
print("Scalar Product:")
print(matx1 * 2)
print("\n")
print("Dot Product:")
print(np.dot(matx1, matx2))

Scalar Product:
[[ 0  2  4]
 [ 6  8 10]]


Dot Product:
[[10 13]
 [28 40]]


**Önemli:** matris çarpımı yalnızca matris elemanlarının birebir çapımına eşit değildir.

- İki eşit boyutlu vektör $\mathbf{x}$ ve $\mathbf{y}$ arasındaki iç çarpım, $\mathbf{x^T y}$ ifadesiyle belirtilen matris çarpımına eşittir.
- $\normalsize\boldsymbol{C = AB}$ şeklindeki matris çarpımını, $\large\boldsymbol{C_{i,j}}$ ifadesini $\normalsize\boldsymbol{A}$ matrisinin i'inci satırının ve B matrisinin j'inci sütununun iç çarpımı olarak hesaplayarak gösterebiliriz.

Matris çarpımı,
- Dağılma özelliğine sahiptir.
$$ \normalsize\boldsymbol{A}\normalsize\boldsymbol{(B+C \ )} = \normalsize\boldsymbol{AB+AC} $$
- Birleşme özelliğine sahiptir.
$$\normalsize\boldsymbol{A(BC \ ) = (AB \ )C}$$
- Değişme özelliğine sahip değildir.
- Bir matrisin transpozu basit olarak  $(AB)^T = B^T A^T$  şeklinde ifade edilir.

In [20]:
# Transpoz işlemi

print("1. Matris")
print(matx1)
print("\n")
print("1. Matris için Traspoz işlemi:")
print(matx1.T)
print("\n")
print("------------------------------")
print("\n")
print("2. Matris")
print(matx2)
print("\n")
print("2. Matris için Traspoz işlemi:")
print(matx2.T)
 

1. Matris
[[0 1 2]
 [3 4 5]]


1. Matris için Traspoz işlemi:
[[0 3]
 [1 4]
 [2 5]]


------------------------------


2. Matris
[[0 1]
 [2 3]
 [4 5]]


2. Matris için Traspoz işlemi:
[[0 2 4]
 [1 3 5]]


$(AB)^T = B^T A^T$

In [21]:
from IPython.display import display, Math
display(Math(r'(AB)^T :'))

print(np.dot(matx1, matx2).T) 

<IPython.core.display.Math object>

[[10 28]
 [13 40]]


In [22]:
display(Math(r'B^T A^T :'))

print(np.dot(matx2.T,matx1.T))

<IPython.core.display.Math object>

[[10 28]
 [13 40]]


- Matris çarpımı, skaler çarpımın aksine değişme özelliğine sahip değildir.
- Yani, $(AB \neq BA)$

In [23]:
np.dot(matx1,matx2)

array([[10, 13],
       [28, 40]])

In [24]:
np.dot(matx2,matx1)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

- Vektörler arasındaki iç çarpım değişme özelliğine sahiptir:
    - $\mathbf{x^T y = y^T x}$

In [25]:
vec1 = np.array([1, 2, 3, 4, 5])
vec2 = np.array([7, 8, 9, 10, 11])

In [26]:
np.dot(vec1.T,vec2)

145

In [27]:
np.dot(vec2.T,vec1)

145

- Yukarıdaki işlemin sonucu skaler olduğu için transpozuda kendisine eşittir.

In [28]:
np.dot(vec1.T,vec2).T

145

#### Birim ve Ters Matrisler

- Birim matrisler, bir vektör ile çarpıldıklarında o vektör üzerinde hiçbir değişiklik yapmayan matrislerdir. n boyutlu vektörler üzerinde işlem yapan birim matrisleri $\mathbf{I_n}$ şeklinde belirtiyoruz. biçimsel olarak bunu, 
$\mathbf{I_n} \in \mathbb{R^{nxn}}$ ve

$$\mathbf{\forall{x}} \in \mathbb{R^n}, \mathbf{I_n x = x}$$ 
şeklinde belirtiyoruz.

- Birim matrislerin, ana köşegen üzerindeki bütün elemanları 1, geriye kalan bütün elemanların değeri ise 0'dır.

- A matrisinin tersi, $A^{-1}$ şeklinde gösterilir ve
$$ A^{-1} A = I_n$$

şeklinde tanımlıdır.

$$ I_3 = \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix} $$

#### Bir matrisin tersini almak:

$$ A = \begin{bmatrix} a & b  \\ c & d\end{bmatrix} $$

$$ A^{-1} = \frac{1}{ad-bc} \begin{bmatrix} d & -b  \\ -c & a\end{bmatrix} $$

$$ A = \begin{bmatrix} 6 & 1  \\ 4 & -2\end{bmatrix} $$

$$ A^{-1} = \frac{1}{(-16)} \begin{bmatrix} -2 & -1  \\ -4 & 6\end{bmatrix} $$

$$ A^{-1} = \begin{bmatrix} 0.125 & 0.0625  \\ 0.25 & -0.375\end{bmatrix} $$

#### Ters Matris

In [29]:
matx3 = np.array([[6, 1], [4, -2]]) #kare matris olmalı
matx3

array([[ 6,  1],
       [ 4, -2]])

In [30]:
ters = np.linalg.inv(matx3) 
print(ters)

[[ 0.125   0.0625]
 [ 0.25   -0.375 ]]


$A^{-1} A = I_n$

In [31]:
#birim = np.dot(matx3, ters)
birim = matx3.dot(ters)
print(birim)

[[1. 0.]
 [0. 1.]]


#### Numpy ile Birim Matris

In [32]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Ters Matrisin Özellikleri

$({A^{-1}})^{-1} = A$

In [33]:
ters = np.linalg.inv(matx3) 
print(ters)

[[ 0.125   0.0625]
 [ 0.25   -0.375 ]]


In [34]:
ters2 = np.linalg.inv(ters) 
print(ters2)

[[ 6.  1.]
 [ 4. -2.]]


$({A^{T}})^{-1} = ({A^{-1}})^{T}$

In [35]:
np.linalg.inv(matx3.T)

array([[ 0.125 ,  0.25  ],
       [ 0.0625, -0.375 ]])

In [36]:
np.linalg.inv(matx3).T

array([[ 0.125 ,  0.25  ],
       [ 0.0625, -0.375 ]])

**Kaynaklar:**
- Bu ders içeriği yararlanılan kaynaklar:
    - Derin Öğrenme (Buzdağı Yayınevi)
    - Python ile Derin Öğrenme (Buzdağı Yayınevi)